# Generated by Django 5.0.6 on 2024-06-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_date_of_birth_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
